# version: "3.8"
services:
  book-service:
    build: ./book_service
    image: book-service:latest
    container_name: book-service
    ports: 
      - 3000:3000
    networks:
      - app-network
    environment:
      - DATABASE_URL=mongodb://book-service-db:27017/books
    depends_on:
      - book-service-db
  
  book-service-db:
    image: mongo:latest
    container_name: book-service-db
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    

networks:
  app-network:
    driver: bridge


volumes:
  mongo-data: